version: "3.7"                
services:                  
  db:                    
    image: postgres:10
    restart: on-failure
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: DatabasePassword

  app:
    image: gocalc:latest
    restart: on-failure
    command: sh -c "/wait && /app"
    depends_on:
      - db
    environment:
      POSTGRES_URI: "postgres://user:DatabasePassword@db/postgres?sslmode=disable"
      WAIT_HOSTS: "db:5432"
      WAIT_BEFORE: "5"
  frontend:
    image: nginx:stable   
    restart: on-failure               
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - db
      - app
