version: "3"                
services:                  
  frontend:                    
    image: nginx:stable
    ports:
      - "127.0.0.1:18888:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf