version: "3.7"

networks:
  database_network:
  web_network:

services:
  mysql:
    image: mysql:5.7
    restart: on-failure
    networks:
      - database_network
    environment:
      MYSQL_DATABASE: voting
      MYSQL_USER: voting
      MYSQL_PASSWORD: voting
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"

  redis:
    image: redis:7.0.2-alpine
    networks:
      - database_network
    restart: on-failure

  voting:
    build: ./voting
    image: voting:local
    expose:
      - 9000
    networks:
      - database_network
      - web_network
    restart: on-failure
    depends_on:
      - mysql
      - redis
    env_file: ./voting/.env.dist

  nginx:
    image: nginx:1.23.0-alpine
    networks:
      - web_network
    restart: on-failure
    ports:
      - "127.0.0.1:20000:80"
    volumes:
      - ./voting/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mysql
      - redis
      - voting